name: Build LineageOS ROM

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Checkout your repository content

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Dependencies
        run: |
          mkdir -p ~/bin
          touch ~/bin/repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          if [ -d "$HOME/bin" ] ; then
          PATH="$HOME/bin:$PATH"
          fi
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          git lfs install
          
      - name: Initialize LineageOS build environment
        run: |
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-17.1 --git-lfs          
          cd android
          mkdir -p .repo/local_manifests
          cp .github/workflows/s2.xml .repo/local_manifests/
          repo sync


      - name: Start the build
        run: |
          cd android
          source build/envsetup.sh
          lunch lineage_s2-release

      - name: Upload ROM
        uses: actions/upload-artifact@v2
        with:
          name: lineageos-s2-ROM.zip
          path: out/target/product/s2/lineage-*.zip
