name: Build LineageOS ROM

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Checkout your repository content

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Initialize LineageOS build environment
        run: |
          git clone https://github.com/LineageOS/android.git -b lineage-18.1 --depth 1
          cd android
          git clone https://github.com/LineageOS/android_device_leeco_s2.git device/leeco/s2  # Adjust the path as necessary
          # Clone other device specific repos similarly
          source build/envsetup.sh
          breakfast s2

      - name: Start the build
        run: |
          cd android
          brunch s2

      - name: Upload ROM
        uses: actions/upload-artifact@v2
        with:
          name: lineageos-s2-ROM.zip
          path: out/target/product/s2/lineage-*.zip
